import json
import os

translations = {
    "Actions": "Aksi",
    "RESET PASSWORD": "RESET PASSWORD",
    "No User data yet.": "Belum ada data User.",
    "Email Sent": "Email Terkirim",
    "Hello,": "Halo,",
    "Search PFE ID, location, or status...": "Cari ID APAR, lokasi, atau status...",
    "LOCATION": "LOKASI",
    "Change Photo": "Ubah Foto",
    "Search...": "Cari...",
    "Date": "Tanggal",
    "Broken / Service": "Rusak / Servis",
    "View your profile": "Lihat profil Anda",
    "Expired DATE": "TANGGAL KADALUARSA",
    "Inspect Entire Building": "Inspeksi Seluruh Gedung",
    "Select Capacity": "Pilih Kapasitas",
    "EXPIRED": "KADALUARSA",
    "Placement List": "Daftar Penempatan",
    "Scan Another PFE": "Scan APAR Lainnya",
    "No building yet.": "Belum ada gedung.",
    "Needs Repair": "Perlu Perbaikan",
    "Add Building": "Tambah Gedung",
    "Month": "Bulan",
    "There are some errors:": "Terdapat beberapa kesalahan:",
    "Module": "Modul",
    "Coming Soon": "Akan Datang",
    "Location Name": "Nama Lokasi",
    "Are you sure you want to delete this building? All locations inside it will also be deleted!": "Yakin ingin menghapus gedung ini? Semua lokasi di dalamnya juga akan terhapus!",
    "No inspection activity yet.": "Belum ada aktivitas inspeksi.",
    "Create Schedule": "Buat Jadwal",
    "Edit": "Edit",
    "PFE Monitoring Control System User Data Report": "Laporan Data User PFE Monitoring Control System",
    "Good Condition": "Kondisi Baik",
    "Forgot Password?": "Lupa Password?",
    "User": "User",
    "Conclusion & Documentation": "Kesimpulan & Dokumentasi",
    "Total Inspections": "Total Inspeksi",
    "Not found.": "Tidak ditemukan.",
    "(Type)": "(Jenis)",
    "Vendor name (Optional)": "Nama vendor (Opsional)",
    "Expires in": "Kadaluarsa dalam",
    "Add Type": "Tambah Jenis",
    "Create New Inspection Schedule": "Buat Jadwal Inspeksi Baru",
    "Login to System Now": "Masuk ke Sistem Sekarang",
    "has been successfully saved.": "telah berhasil disimpan.",
    "Export Excel": "Export Excel",
    "No location yet.": "Belum ada lokasi.",
    "SETUP SUCCESSFUL": "SETUP BERHASIL",
    "Year": "Tahun",
    "TAKE PHOTO IN LANDSCAPE": "AMBIL FOTO DALAM POSISI LANDSCAPE",
    "Add Location": "Tambah Lokasi",
    "Delete": "Hapus",
    "Repeat the password above": "Ulangi password di atas",
    "Print All PFE QR Codes": "Cetak Semua QR Code APAR",
    "Update password": "Update password",
    "Unassigned": "Belum ditugaskan",
    "Danger": "Bahaya",
    "Condition": "Kondisi",
    "Record physical and functional check results of PFE components": "Catat hasil pengecekan fisik dan fungsi komponen APAR",
    "No activity log yet.": "Belum ada log aktivitas.",
    "Select Location": "Pilih Lokasi",
    "Delete Schedule?": "Hapus Jadwal?",
    "Repair": "Perbaikan",
    "Type to add new location": "Ketik untuk menambah lokasi baru",
    "Select Type": "Pilih Jenis",
    "Enter your email": "Masukkan email Anda",
    "Inspected By": "Diinspeksi Oleh",
    "Back to Login": "Kembali ke Login",
    "Export PDF": "Export PDF",
    "Enter your email and we will send a link to reset your password.": "Masukkan email Anda dan kami akan mengirimkan tautan untuk mengatur ulang kata sandi.",
    "PROGRESS": "PROSES",
    "Process": "Proses",
    "Delete Schedule": "Hapus Jadwal",
    "Missed": "Terlewat",
    "Edit Building Data": "Edit Data Gedung",
    "Success": "Berhasil",
    "Add User": "Tambah User",
    "results": "hasil",
    "Answer each point according to actual condition in the field.": "Jawab setiap poin sesuai kondisi aktual di lapangan.",
    "Camera cannot be accessed or is blocked. Make sure to grant camera permissions.": "Kamera tidak dapat diakses atau diblokir. Pastikan Anda memberikan izin kamera.",
    "Select Date": "Pilih Tanggal",
    "Your account password has been successfully created and safely stored.": "Kata sandi akun Anda telah berhasil dibuat dan disimpan dengan aman.",
    "(Automatic)": "(Otomatis)",
    "No PFE in this area.": "Tidak ada APAR di area ini.",
    "Inspect Specific Location": "Inspeksi Lokasi Spesifik",
    "No PFE or Building data yet.": "Belum ada data APAR atau Gedung.",
    "Schedule Type": "Jenis Jadwal",
    "All Types": "Semua Jenis",
    "PFE units ready to print on label/sticker paper": "Unit APAR siap cetak di kertas label/stiker",
    "Completed on": "Selesai pada",
    "COMPLETED": "SELESAI",
    "PFE Inspection Results": "Hasil Inspeksi APAR",
    "Save Schedule": "Simpan Jadwal",
    "Uninspected": "Belum Diinspeksi",
    "User Data": "Data User",
    "No data for this period and filter.": "Tidak ada data untuk periode dan filter ini.",
    "Not Main PIC for this Area": "Bukan PIC Utama Area Ini",
    "Location Scope": "Cakupan Area",
    "Success!": "Berhasil!",
    "Completed": "Selesai",
    "Description": "Keterangan",
    "MISSED": "TERLEWAT",
    "EXPIRED DATE": "TANGGAL KADALUARSA",
    "Registered Email": "Email Terdaftar",
    "selected locations": "lokasi terpilih",
    "All Statuses": "Semua Status",
    "No PFE data available": "Belum ada data APAR",
    "Missed Schedule": "Jadwal Terlewat",
    "Scheduled": "Terjadwal",
    "Save Password": "Simpan Password",
    "TODAY": "HARI INI",
    "Free / Anyone": "Bebas / Siapa Saja",
    "Point camera at PFE QR Code": "Arahkan kamera ke QR Code APAR",
    "REPAIR": "PERBAIKAN",
    "Account Email": "Email Akun",
    "Please create a password for your account.": "Silakan buat kata sandi untuk akun Anda.",
    "pagination.next": "Berikutnya &raquo;",
    "Select Officer": "Pilih Petugas",
    "Add Capacity": "Tambah Kapasitas",
    "Search officer...": "Cari petugas...",
    "No important notifications.": "Belum ada pemberitahuan penting.",
    "Month Ended": "Bulan Berakhir",
    "No upcoming inspection schedule yet.": "Belum ada jadwal inspeksi mendatang.",
    "Completed Schedule": "Jadwal Selesai",
    "Type Name": "Nama Jenis",
    "Focus on area...": "Fokuskan pada area...",
    "Edit Inspection Schedule": "Edit Jadwal Inspeksi",
    "Enter sequence number...": "Masukkan nomor urut...",
    "WAITING": "MENUNGGU",
    "Take Photo": "Ambil Foto",
    "Search building...": "Cari gedung...",
    "Update PFE Data": "Perbarui Data APAR",
    "Inspection data for PFE": "Data inspeksi untuk APAR",
    "Building Name": "Nama Gedung",
    "Constraint:": "Kendala:",
    "Upcoming Schedule List": "Daftar Jadwal Mendatang",
    "Last!": "Terakhir!",
    "This user will be permanently deleted!": "User ini akan dihapus secara permanen!",
    "Enter PIN from Email": "Masukkan PIN dari Email",
    "Minimum 8 characters": "Minimal 8 karakter",
    "No activity history yet.": "Belum ada riwayat aktivitas.",
    "All PFE have been inspected this month! 🎉": "Semua APAR telah diinspeksi bulan ini! 🎉",
    "Inspection Completed": "Inspeksi Selesai",
    "Logistics Warehouse": "Gudang Logistik",
    "Login": "Masuk",
    "Area Scope (Building)": "Cakupan Area (Gedung)",
    "PFE Inspection Report": "Laporan Inspeksi APAR",
    "Determine area, date, and inspection officer.": "Tentukan area, tanggal, dan petugas inspeksi.",
    "Oops, An Error Occurred!": "Oops, Terjadi Kesalahan!",
    "Special Inspection / Findings": "Inspeksi Khusus / Temuan",
    "Inspection Completed!": "Inspeksi Selesai!",
    "Oops, an error occurred!": "Oops, Terjadi Kesalahan!",
    "Today\\'s Schedule": "Jadwal Hari Ini",
    "pagination.previous": "&laquo; Sebelumnya",
    "Expiration Date": "Tanggal Kadaluarsa",
    "Create Inspection Schedule": "Buat Jadwal Inspeksi",
    "No registered PFE data available.": "Belum ada data APAR terdaftar.",
    "All Areas": "Semua Area",
    "Update area, date, and inspection officer.": "Perbarui area, tanggal, dan petugas inspeksi.",
    "Forgot Password": "Lupa Kata Sandi",
    "Enter quantity": "Masukkan ukuran",
    "Verify PIN": "Verifikasi PIN",
    "Example: user@bbraun.com": "Contoh: user@bbraun.com",
    "Example: Focus on PFE in kitchen and generator area.": "Contoh: Fokuskan pada APAR di area dapur dan genset.",
    "No chart data available": "Belum ada data grafik",
    "Production Building": "Gedung Produksi",
    "Overall Status": "Status Keseluruhan",
    "Select / Type New": "Pilih / Ketik Baru",
    "to": "hingga",
    "Name": "Nama",
    "Manage and monitor PFE checking routines": "Kelola dan pantau rutinitas pengecekan APAR",
    "History of user actions in the system": "Riwayat tindakan user di sistem",
    "PIN and password creation instructions will be sent automatically to the user\\'s email after the account is created.": "Instruksi pembuatan PIN dan kata sandi akan dikirim otomatis ke email user setelah akun dibuat.",
    "Search location...": "Cari lokasi...",
    "Write notes...": "Tulis keterangan...",
    "Yes": "Ya",
    "History of the 5 most recent inspections": "Riwayat 5 inspeksi terakhir",
    "PFE Number": "Nomor APAR",
    "Checking Officer": "Petugas Pemeriksa",
    "Start Inspection": "Mulai Inspeksi",
    "Routine: Date": "Rutin: Tgl",
    "No data for this period.": "Tidak ada data untuk periode ini.",
    "Waiting": "Menunggu",
    "Please create a new password for your account.": "Silakan buat kata sandi baru untuk akun Anda.",
    "Recapitulation of monthly inspection data": "Rekapitulasi data inspeksi bulanan",
    "Routine Monthly Inspection": "Inspeksi Rutin Bulanan",
    "Additional Notes": "Catatan Tambahan",
    "Inspection Date": "Tanggal Inspeksi",
    "New Password": "Password Baru",
    "PASS": "BAIK",
    "Pagination Navigation": "Navigasi Halaman",
    "Condition Photo": "Foto Kondisi",
    "Expired!": "Kadaluarsa!",
    "Edit Schedule": "Edit Jadwal",
    "Routine Inspection": "Inspeksi Rutin",
    "Empty": "Kosong",
    "Edit PFE Data": "Edit Data APAR",
    "All Capacities": "Semua Kapasitas",
    "Select Schedule Type": "Pilih Jenis Jadwal",
    "Inspected": "Sudah Diinspeksi",
    "data": "data",
    "Additional Notes (Optional)": "Catatan Tambahan (Opsional)",
    "Are you sure you want to delete this location?": "Yakin ingin menghapus lokasi ini?",
    "Deleted schedule cannot be restored!": "Jadwal yang dihapus tidak dapat dikembalikan!",
    "Inspection Officer": "Petugas Inspeksi",
    "PIN Verified": "PIN Terverifikasi",
    "(All Areas)": "(Semua Area)",
    "Write other general observation notes...": "Tulis catatan umum lainnya...",
    "Officer:": "Petugas:",
    "Complete Inspection": "Selesaikan Inspeksi",
    "Specific": "Spesifik",
    "Main Building (Already scheduled)": "Gedung Utama (Sudah dijadwalkan)",
    "Inspection Checklist": "Checklist Inspeksi",
    "Inspection Photo": "Foto Inspeksi",
    "Send Reset Link": "Kirim Link Reset",
    "Deleted Location": "Lokasi Terhapus",
    "Needs Refill": "Perlu Isi Ulang",
    "Inspection Progress": "Progress Inspeksi",
    "PROCESS": "PROSES",
    "Additional Notes:": "Catatan Tambahan:",
    "Notes & Officer": "Catatan & Petugas",
    "No results found": "Tidak ada hasil yang ditemukan",
    "Determine area, date, and officer for routine/special inspection": "Tentukan area, tanggal, dan petugas untuk inspeksi rutin/khusus",
    "No PFE data available.": "Belum ada data APAR.",
    "PFE Inspection Form": "Formulir Inspeksi APAR",
    "Reset Password": "Reset Password",
    "Select Scope Area": "Pilih Area Cakupan",
    "PFE MONITORING SYSTEM": "SISTEM MONITORING APAR",
    "Deleted Building": "Gedung Terhapus",
    "Type": "Jenis",
    "Inspection PIN (6 Digits)": "PIN Inspeksi (6 Digit)",
    "No specific notes.": "Tidak ada catatan khusus.",
    "Immediate": "Segera",
    "Status & Inspection Date": "Status & Tanggal Inspeksi",
    "BUILDING": "GEDUNG",
    "Checklist": "Checklist",
    "Inspection Schedule": "Jadwal Inspeksi"
}

lang_id_path = "c:/laragon/www/APARB.Braun/lang/id.json"
lang_en_path = "c:/laragon/www/APARB.Braun/lang/en.json"

with open(lang_id_path, "r", encoding="utf-8") as f:
    id_lang = json.load(f)

for k, v in translations.items():
    id_lang[k] = v

with open(lang_id_path, "w", encoding="utf-8") as f:
    json.dump(id_lang, f, indent=4, ensure_ascii=False)

with open(lang_en_path, "r", encoding="utf-8") as f:
    en_lang = json.load(f)

for k, v in translations.items():
    if k not in en_lang:
        en_lang[k] = k

with open(lang_en_path, "w", encoding="utf-8") as f:
    json.dump(en_lang, f, indent=4, ensure_ascii=False)

print("Dictionaries updated successfully!")
